libs = ['opencv_core', 'opencv_imgproc', 'opencv_ximgproc',
        'opencv_highgui', 'opencv_imgcodecs', 'opencv_videoio']

env = Environment(CPPPATH=['/usr/include/boost/', '/usr/local/include/opencv4'],
                  CPPDEFINES=[],
                  LIBS=libs,
                  SCONS_CXX_STANDARD="c++14"
                  )

env.Program('test', Glob('src/*.cpp'))
